[6기 my_U] TodoList with CRUD
next-step/js-todo-list-step1 pull request #117
Opened 2021-01-26 09:25 UTC by my-U

# 🎯 미션

## 🎯 요구사항

- [x] todo list에 todoItem을 키보드로 입력하여 추가하기
- [x] todo list의 체크박스를 클릭하여 complete 상태로 변경. (li tag 에 completed class 추가, input 태그에 checked 속성 추가)
- [x] todo list의 x버튼을 이용해서 해당 엘리먼트를 삭제
- [x] todo list를 더블클릭했을 때 input 모드로 변경. (li tag 에 editing class 추가) 단 이때 수정을 완료하지 않은 상태에서 esc키를 누르면 수정되지 않은 채로 다시 view 모드로 복귀
- [x] todo list의 item갯수를 count한 갯수를 리스트의 하단에 보여주기
- [x] todo list의 상태값을 확인하여, 해야할 일과, 완료한 일을 클릭하면 해당 상태의 아이템만 보여주기

## 🎯🎯 심화 요구사항

- [ ] localStorage에 데이터를 저장하여, TodoItem의 CRUD를 반영하기. 따라서 새로고침하여도 저장된 데이터를 확인할 수 있어야 함

## 후기
두 번째 참여인데 이전에 받았던 리뷰들을 참고하여 만드려고 노력하였지만 역시 어렵네요.. 
아직 많이 부족하지만 많은 피드백 부탁드립니다.

2021-01-27 08:09 UTC, YUJO42 reviewed
코드 잘 봤습니다! 저도 ```localStorage```에 저장하는 부분에서 많이 헤맸었는데  지금 작성하신 코드의 ```TodoItemList```배열을 ```JSON.stringfy()```메소드를 통해 저장하고 ```JSON.parse()```를 통해 불러와서 사용하는 방식을 적용하면 몇줄의 코드 변경으로 ```localStorage```를 사용하실 수 있을거 같습니다! 

고생하셨습니다!!

2021-01-27 08:09 UTC, YUJO42 commented on todoList.js
> +        if(TodoItemName.lenght !== 0) {
해당 조건문을 if 문 밖으로 빼서 
```js
if (e.key === 'Enter' && TodoItemName.length)
```
이런 식으로 조건문을 합쳐주면 가독성이 좋아질거 같습니다!

2021-01-27 08:48 UTC, hwookim reviewed
몇가지 리뷰 남겼습니다. DM도 괜찮으니 궁금하신 건 얼마든지 질문해주세요! 😄

2021-01-27 08:48 UTC, hwookim commented on todoList.js
> +    const $TodoItem = target.parentNode.parentNode;
가장 가까운 `li` 태그를 찾거나 `li` 태그에 클래스를 등록해서 해당 클래스를 찾아보는 건 어떨까요?
`Element.cloest`함수가 도움될거예요.

2021-01-27 08:48 UTC, hwookim commented on todoList.js
> +  });
실제 표현되는 DOM의 관리와 TodoItemList의 관리가 별도로 이루어지고 있네요.
지금은 그럴 일은 없겠지만, 코드가 길어지면서 중간에 오류가 발생하면 관리가 힘들어질 수도 있을 것 같아요.
같은 라이프 사이클에 있는 대상들은 한번에 관리하면 어떨까요?

2021-01-27 08:48 UTC, hwookim commented on todoList.js
> +const allShow = () => { // 전체보기
함수의 네이밍은 동사의 형태를 띄는게 일반적입니다.😄
다른 함수들과 같이 `~Show` 친구들도 동사형으로 바꿔보는 건 어떨까요?

2021-01-27 12:33 UTC, DongHwani reviewed
코드 잘 봤습니다 :) 👍  마이유님 코드 보면서 저도 많이 배우고 갑니다! 
코드리뷰는 생소한 경험이어서 간략한 질문 코멘트 남기고 갑니다 :)

2021-01-27 12:33 UTC, DongHwani commented on todoList.js
> +const $TodoCount = document.querySelector('span > strong');
셀렉터에 대한 변수명을 `$` 표시 후에 첫 문자가 대문자인것도 있고 소문자 형식도 있는데요. 이렇게 지정하신 이유가 따로 있을까요? 제가 자바스크립트에 대한 코딩컨벤션 지식이 많이 부족해서 문의하나 드립니다! :)

2021-01-27 13:35 UTC, imakerjun requested changes
@my-U 님~! 쉽지 않았을텐데 열심히 참여해주시고 PR까지 보내주셔서 너무 감사드립니다! ㅎㅎ 마지막 미션까지 같이 힘내서 완성하면 좋을 것 같아요 💪🏻 
다른분들이 좋은 피드백 많이 남겨주셔서 중복되지 않는 부분들만 몇가지 피드백 남겨보았어요 이번에 바로 적용하기 어려우시면 다음 미션에 반영해주시면 좋을 것 같습니다!

남은 기간도 화이팅입니다!!

2021-01-27 13:35 UTC, imakerjun commented on todoList.js
> +  $activeTodo.addEventListener('click', activeShow);
한곳에 정리되어 있으니 너무 좋은것 같아요! 단 함수 이름이 `initEventListener`이면 더 의미가 명확할 것 같아요!

2021-01-27 13:35 UTC, imakerjun commented on todoList.js
> +let TodoItemList = []; // $TodoInput에 입력되는 내용들을 저장
주석은 꼭 필요한 경우만 남겨주시는면 더 간결해지고, 다른 사람들과 협업하기 좋은 코드가 될 것 같아요  😄

2021-01-27 13:35 UTC, imakerjun commented on todoList.js
> +    if($TodoItem.className !== 'completed') {
`className`을 다룰때는 `classList`에 있는 메서드를 사용하시는게 좋습니다. className은 전체 class들을 하나의 string으로 return해주기 때문에 새로운 css가 추가되면 원치않게 에러가 날 수 있을 것 같아요~!

https://developer.mozilla.org/ko/docs/Web/API/Element/classList

2021-01-27 13:35 UTC, imakerjun commented on todoList.js
> +    }
가능하면 eventListener에 할당하는 콜백함수의 경우 inline으로 쓰시기보다는 함수로 분리하는 것을 추천드립니다. 왜냐하면 inline으로 작성하면 해당 콜백함수가 어떤 기능을 하는지 모두 읽어봐야하는데, 함수로 분리하면 함수명만 보고 어떤 동작을 하는지 한눈에 더 알기 쉽기 때문이에요!

2021-01-27 13:35 UTC, imakerjun commented on todoList.js
> +    $activeTodo.classList.remove('selected');
여기서 return을 해주시면 굳이 아래의 if문의 조건을 판별하는데 메모리를 사용할 필요가 없을 것 같아요 😄

2021-01-27 13:35 UTC, imakerjun commented on todoList.js
> +  $TodoItems.forEach(function(TodoItem) {
다른 곳과 마찬가지로 익명함수로 통일 시켜주시면 좋을 것 같습니다!

2021-01-27 13:35 UTC, imakerjun commented on todoList.js
> +
불필요한 공백라인이 많은 것 같아요 😢 삭제해주시면 더 깔끔해질 것 같아요~!

2021-01-29 07:54 UTC, my-U commented on todoList.js
> +  $TodoItems.forEach(function(TodoItem) {
좋은 지적 감사합니다!

2021-02-23 12:41 UTC, merged