[6기 WOO] TodoList with CRUD
next-step/js-todo-list-step1 pull request #119
Opened 2021-01-26 09:29 UTC by hwookim

## 🚀 기본 요구사항

- [x] todo list에 todoItem을 키보드로 입력하여 추가하기
- [x] todo list의 체크박스를 클릭하여 complete 상태로 변경. (li tag 에 completed class 추가, input 태그에 checked 속성 추가)
- [x] todo list의 x버튼을 이용해서 해당 엘리먼트를 삭제
- [x] todo list를 더블클릭했을 때 input 모드로 변경. (li tag 에 editing class 추가) 단 이때 수정을 완료하지 않은 상태에서 esc키를 누르면 수정되지 않은 채로 다시 view 모드로 복귀
- [x] todo list의 item갯수를 count한 갯수를 리스트의 하단에 보여주기
- [x] todo list의 상태값을 확인하여, 해야할 일과, 완료한 일을 클릭하면 해당 상태의 아이템만 보여주기

## 🚀🚀 심화 요구사항

- [x] localStorage에 데이터를 저장하여, TodoItem의 CRUD를 반영하기. 따라서 새로고침하여도 저장된 데이터를 확인할 수 있어야 함

---

약간 늦은 감이 있지만... 빠듯하게 오늘 스터디 시간 전에 리뷰 요청 드려봅니다! 😅

TodoApp 구현은 매번 할 때마다 새로운 방식을 시도해보려고 하는데, 이번에는 좀 무난하게 한 듯 하네요.
Html 객체에도 $를 달고, 전역으로 사용하는 store에도 $를 달다보니 좀 헷갈리는 것 같아요. 어떻게 하는 게 좋을 지 고민입니다.
그냥 Html 객체에는 $를 빼는 게 나으려나요..🤔

부족한 게 많은 코드입니다.
따끔한 지적, 비판 부탁드리겠습니다!! 😄

2021-01-27 18:52 UTC, YUJO42 requested changes
![image](https://user-images.githubusercontent.com/61097373/106037133-9a8de800-6119-11eb-8037-457fe7d7b4fd.png)

코드를 받아서 실행시켜보니 위와 같은 에러와 함께 실행이 안 되네요! 확인이 필요해보입니다!

코드가 모듈화 되어있기는 하지만 Todo, todo, TodoList, TodoListItem 등 비슷한 모듈명이 많아 가독성이 다소 떨어진다는 느낌을 받았습니다! 모듈을 기능이나 동작 단위로 분리하고 네이밍을 수행하는 기능과 연관되어 해주신다면 더욱 읽기 좋은 코드가 될거 같습니다!

고생하셨습니다!!👍👍👍

2021-01-27 18:52 UTC, YUJO42 commented on src/component/TodoInput.js
> +    }
```suggestion
    if (key !== "Enter" || !target.value.trim()) {
      return;
    }
```

```false``` 조건이 많지 않아 이런 식으로 한번의 조건문으로 검사하는게 코드가 더 깔끔해질거 같습니다!

2021-01-27 18:52 UTC, YUJO42 commented on src/component/TodoListItem.js
> +    }
이 부분 역시 조건문을 하나만 사용하시면 더 깔끔해질거 같습니다!

2021-01-27 18:52 UTC, YUJO42 commented on src/domain/Todo.js
> +export default class Todo {
개인적으로는 ```Todo```라는 모듈과 ```todo```라는 모듈이 둘 다 존재해서 코드를 보면서 가독성이 조금 떨어진다는 생각을 했습니다! 모듈의 역할을 명확히 정하고 다른 방식으로 네이밍 해주신다면 코드의 가독성이 더 좋아질거 같습니다!

2021-01-27 18:52 UTC, YUJO42 commented on src/store/module/todo.js
> +  let nextId = items[items.length - 1]._id + 1;
현재 코드를 실행시켰을 때 이 부분에서 에러가 발생하는데 한번 확인해주시면 좋을거 같습니다!

2021-01-27 18:52 UTC, YUJO42 commented on src/store/module/todo.js
> +  };
```suggestion
  const deleteItem = (targetId) => {
    const newItmes = items.filter((item) => item.id !== targetId);
    storage.setStorage(newItems);
  };
```

변수명을 명확히하고 상황에 맞는 적절한 메서드를 활용하면 더 가독성 높은 코드가 될거 같습니다!

2021-01-27 18:52 UTC, YUJO42 commented on src/component/TodoFilter.js
> +    target.classList.add("selected");
```suggestion
    const $previous = $filter.querySelector(".selected");
    $previous.classList.toggle('selected')
```

```classList.toggle()```메서드를 사용하면 보다 간결하게 작성 가능할거 같습니다!

2021-01-28 08:42 UTC, hwookim commented on src/store/module/todo.js
> +  };
현재의 프로그램은 초기에 한번만 localStorage에서 데이터를 호출하고 이후에는 저장만 하는 방식을 취하고 있습니다.
splice가 아닌 filter로 바꾸게 된다면 원본 배열은 변하지 않기 때문에 todo 에서 가지고 있는 items가 의미없게 되겠네요.🤔

api로 치환하고 외부 데이터를 호출한다고 생각했을 때, 외부에서 변경될 가능성이 있으니 내부 데이터 보다는 외부 데이터를 우선 시 하는 게 맞는 것 같기도 하군요.
todo의 items를 지우고 getItems() 함수를 생성해 매번 데이터를 호출하도록 변경했습니다.

좋은 리뷰 감사드려요 😄

2021-01-28 08:44 UTC, hwookim commented on src/store/module/todo.js
> +  let nextId = items[items.length - 1]._id + 1;
`items`에 아무것도 존재하지 않을 때 `id + 1`이 불가능해서 생기는 오류였네요.😅
수정했습니다!

2021-01-28 09:15 UTC, hwookim commented on src/component/TodoInput.js
> +    }
개인적인 이벤트리스너 함수의 작성법이긴 합니다만...🤔

이벤트리스너 함수의 경우 두가지 부분으로 나눌 수 있다고 생각합니다.

- 이벤트를 target보다 상위에 등록했을 경우 올바른 target이 잡혔는지 검사하거나 key 이벤트의 경우에 keyCode를 확인하는 등, 이벤트의 실행 여부 자체를 검사하는 부분
- 실제로 동작하는 부분

이렇게요.

이 경우에 저는 contents를 추출하는 순간부터 실행 여부가 아닌 실제 실행부라고 판단해 이렇게 나눴는데.....
막상 이렇게 쓰다보니까 스스로도 좀 헷갈리는 부분이긴 하네요.🤔
조금 더 고민해보도록 하겠습니다! 😅

좋은 의견 감사해요 ㅎㅎ

2021-01-28 09:19 UTC, hwookim commented on src/component/TodoFilter.js
> +    target.classList.add("selected");
해당 부분은 toggle과는 성격이 다른 로직으로 보입니다.
toggle이라 함은 있을 경우 지우고 없을 경우 만드는 것, 분기처리까지 포함한 것이 주 목적인데,
해당 로직은 분기의 성격이 없습니다.
이전에 선택되었던 필터에 **확실하게 있는** 클래스를 지우고, 새로 선택되어야하는 필터에 **확실하게 없는** 클래스를 추가하는 것이니까요.

물론 일부 취향차이와 견해 차이입니다만...🤔

2021-01-28 10:33 UTC, hwookim commented
@YUJO42 
리뷰 감사드립니다! 생각해야할 부분이 많군요.😄

말씀해주신 TodoList, TodoListItem과 기능단위 모듈의 분리에 관해서는 저는 다른 생각이라 이렇게 별도로 코멘트 남깁니다!
저도 공부하는 입장이라 제 생각이 틀릴 수도 있습니다. 참고 바래요..ㅎㅎ😅

Vue나 React같은 프레임워크에 익숙해지다보니 기본적으로 컴포넌트를 기반으로 모듈을 분리했는데요.
컴포넌트를 기반으로 작성할 경우, 연관되는 컴포넌트끼리는 비슷한 네이밍을 통해 그 관계성을 드러내기도 합니다.
실제로 [Vue 공식 스타일 가이드](https://kr.vuejs.org/v2/style-guide/index.html#%EA%B0%95%ED%95%9C-%EC%97%B0%EA%B4%80%EC%84%B1%EC%9D%84-%EA%B0%80%EC%A7%84-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EC%9D%B4%EB%A6%84-%EB%A7%A4%EC%9A%B0-%EC%B6%94%EC%B2%9C%ED%95%A8)에서도 위와 같은 방법을 추천하고 있고요.

한 컴포넌트 내에서 사용될 기능들을 모듈 단위로 분리하게 될 때, 각 모듈별로 공통되는 부분이 많아질 우려가 있습니다.
여러 기능이 포함된 `TodoListItem`을 보면 대부분의 함수에서 `Todo` 객체의 `id`값에 접근하고 있는데, 이로 인해 매번 매개변수를 넘겨줘야하는 번거로움이 생길 수도 있죠.
컴포넌트 단위의 모듈 분리의 장점은 응집도의 향상과 결합도의 저하입니다.
자신이 처리할 작업은 최대한 자신의 내부에서 처리하자는 방침이죠.

Todo와 todo에 대해서는... 확실히 오해의 소지가 있지만 대안이 떠오르질 않네요😭
실제 todo 사용 시에는 $store를 통해 접근하기 때문에 좀 괜찮지만, 만약 다른 사람들과 함께 협업할 경우 처음 보자마자 그걸 알아차리긴 힘드니까요.
이 부분은 조금 더 고민해보겠습니다.🤔

좋은 리뷰 정말 감사드립니다!
이 코멘트에 대한 윤호님의 생각도 들려주시면 감사하겠어요...🥰

2021-01-28 11:00 UTC, imakerjun reviewed
역시 @hwookim 님 코드는 컴포넌트도 잘 분리되어 있고, 각각의 컴포넌트 별로 역할이 잘 나뉘어져 있어 코드를 읽기가 너무 좋았습니다! 남은 미션들도 지금처럼 진행해주시면 다른 분들에게도 많은 영감을 더 주시게 될 것 같아요 ㅎㅎ

남은 미션들도 뽜이팅입니다!!!!

2021-01-28 11:50 UTC, YUJO42 commented on src/component/TodoInput.js
> +    }
아하 저런 식으로 생각해서 사용할수도 있겠군요! hwookim님이 말씀해주신 의견도 충분히 설득력 있네요! 

새로운 관점을 하나 배워가네요! 감사합니다!!👍👍👍

2021-01-28 11:52 UTC, YUJO42 commented on src/store/module/todo.js
> +  };
아하 그렇군요! 제가 코드를 꼼꼼히 확인하지 못했네요! todo에서 가지고 있는 items에 대한 부분은 생각 못 했던거 같습니다!

좋은 의견 감사드립니다!!👍👍👍

2021-01-28 11:53 UTC, YUJO42 commented on src/component/TodoFilter.js
> +    target.classList.add("selected");
그렇군요! hwookim님이 말씀주신 것처럼 **확실하게 있는** 클래스를 지우고 **확실하게 없는**클래스를 추가한다는 관점에서 보면 제가 코멘트 남긴 코드보다 훨씬 좋아보이네요!! 감사합니다!!👍👍👍

2021-01-28 11:59 UTC, YUJO42 commented
@hwookim 

안녕하세요! 장문으로 코멘트 남겨주셔서 감사합니다!

저도 공부하는 입장에서 제 의견을 코멘트로 남겼는데 지금 다시 제가 남긴 코멘트를 읽어보니 너무 제 의견만 강하게 피력한거 같아서 죄송합니다ㅠㅠ

저 같은 경우는 Vue나 React같은 프레임워크를 많이 접해보지 않아서 그 부분을 고려하지 못 했네요!

말씀해주신대로 한 컴포넌트 내에서 자신이 처리할 작업을 최대한 처리해서 응집도를 높이고 결합도를 낮춘다는 개념을 처음 알았네요! 

링크로 남겨주신 Vue의 공식 스타일 가이드 문서도 읽어봤는데 말씀해주신대로 컴포넌트를 구성하는 방법도 정말 좋아보이네요! 제 경험이 부족해 비슷한 코드를 많이 접해보지 않아서 가독성이 떨어진다고 느꼈던거 같습니다!

꼼꼼하게 리뷰에 대한 코멘트를 남겨주신 덕분에 평소 생각하지 못 했던 여러 관점에서 다시 한번 생각해보게 되는 계기가 됐네요! 다음 미션에서 기회가 된다면 저 역시 컴포넌트 단위의 모듈 분리를 통한 코드 작성도 한번 시도해봐야곘습니다!!

꼼꼼하게 피드백 주셔서 감사합니다!👍👍👍

2021-02-23 12:42 UTC, merged